package com.lambdaschool.sprint2_challenge

import com.lambdaschool.shoppinglist.R

val itemIds = intArrayOf(
    R.drawable.almond,
    R.drawable.apple_green,
    R.drawable.apple_red,
    R.drawable.apple_yellow,
    R.drawable.apple2,
    R.drawable.artichoke,
    R.drawable.asparagus,
    R.drawable.avocado,
    R.drawable.avocado2,
    R.drawable.bacon,
    R.drawable.banana,
    R.drawable.banana_split,
    R.drawable.barley,
    R.drawable.beans,
    R.drawable.beef,
    R.drawable.beer,
    R.drawable.beer_bottle,
    R.drawable.beetroot,
    R.drawable.bell_pepper,
    R.drawable.bell_pepper_green,
    R.drawable.bell_pepper_yellow,
    R.drawable.bell_pepper1,
    R.drawable.bell_pepper2,
    R.drawable.birthday_cake,
    R.drawable.biscotti,
    R.drawable.blackberry,
    R.drawable.blueberry,
    R.drawable.bowl_chopsticks,
    R.drawable.brazil_nut,
    R.drawable.bread,
    R.drawable.bread_slice,
    R.drawable.broccoli,
    R.drawable.brown_bread,
    R.drawable.bubblegum,
    R.drawable.bubblegum_machine,
    R.drawable.bun,
    R.drawable.butter,
    R.drawable.cabbage,
    R.drawable.cake,
    R.drawable.cake_slice,
    R.drawable.cake_slice2,
    R.drawable.candy,
    R.drawable.candy_cane,
    R.drawable.canned_food,
    R.drawable.cantaloupe,
    R.drawable.cantaloupe1,
    R.drawable.cantaloupe2,
    R.drawable.caramel_apple,
    R.drawable.carrot,
    R.drawable.cashew_nut,
    R.drawable.cassava,
    R.drawable.cassava2,
    R.drawable.cauliflower,
    R.drawable.celery,
    R.drawable.champagne,
    R.drawable.cheese_round,
    R.drawable.cheese_slice,
    R.drawable.cheese_wedge,
    R.drawable.cherry,
    R.drawable.cherry_tomatoes,
    R.drawable.chestnut,
    R.drawable.chicken,
    R.drawable.chicken_leg,
    R.drawable.chickpeas,
    R.drawable.chili_pepper,
    R.drawable.chocolate_bar,
    R.drawable.chocolate_bonbon,
    R.drawable.chocolate_chip_cookie,
    R.drawable.cocktail,
    R.drawable.cocoa,
    R.drawable.coconut,
    R.drawable.coconut2,
    R.drawable.coffee,
    R.drawable.coffee_bean,
    R.drawable.coffee_pot,
    R.drawable.cognac,
    R.drawable.cola_drink,
    R.drawable.cookie,
    R.drawable.cookie2,
    R.drawable.corn_cob,
    R.drawable.cotton_candy,
    R.drawable.crab,
    R.drawable.cracker,
    R.drawable.cranberry,
    R.drawable.croissant,
    R.drawable.cucumber,
    R.drawable.cupcake,
    R.drawable.cutlet,
    R.drawable.double_popsicle,
    R.drawable.doughnut,
    R.drawable.eclair,
    R.drawable.egg,
    R.drawable.eggplant,
    R.drawable.eggplant2,
    R.drawable.fig,
    R.drawable.fig2,
    R.drawable.fish,
    R.drawable.fish_fillet,
    R.drawable.flour,
    R.drawable.french_fries,
    R.drawable.fried_chicken_leg,
    R.drawable.fried_egg,
    R.drawable.frozen,
    R.drawable.fruit_squash,
    R.drawable.fruitcake,
    R.drawable.garlic,
    R.drawable.glass_bottle,
    R.drawable.glass_of_milk,
    R.drawable.goldenberry,
    R.drawable.grapefruit,
    R.drawable.grapefruit2,
    R.drawable.grapes_green,
    R.drawable.grapes_red,
    R.drawable.green_beans,
    R.drawable.ham,
    R.drawable.hamburguer,
    R.drawable.hard_boiled_egg,
    R.drawable.hazelnut,
    R.drawable.honey,
    R.drawable.hot_chocolate,
    R.drawable.hotdog,
    R.drawable.ice_cream_bar,
    R.drawable.ice_cream_cone,
    R.drawable.ice_cream_cup,
    R.drawable.ice_cream_double_cone,
    R.drawable.ice_cubes,
    R.drawable.jam,
    R.drawable.ketchup,
    R.drawable.kiwi2,
    R.drawable.leek,
    R.drawable.lemon,
    R.drawable.lemon2,
    R.drawable.lentils,
    R.drawable.lettuce,
    R.drawable.lime,
    R.drawable.lime2,
    R.drawable.lobster,
    R.drawable.lollipop1,
    R.drawable.macadamia_nut,
    R.drawable.macaron,
    R.drawable.maple_syrup,
    R.drawable.maple_syrup2,
    R.drawable.marshmallow,
    R.drawable.mayonnaise,
    R.drawable.meatballs,
    R.drawable.milk_carton,
    R.drawable.milk_gallon,
    R.drawable.milkshake,
    R.drawable.muffin,
    R.drawable.mushrooms,
    R.drawable.mushrooms2,
    R.drawable.mustard,
    R.drawable.noodles,
    R.drawable.nut_cake,
    R.drawable.oats,
    R.drawable.olives,
    R.drawable.olives_black,
    R.drawable.omelette,
    R.drawable.onion,
    R.drawable.onion_red,
    R.drawable.onion_red2,
    R.drawable.orange,
    R.drawable.orange_juice,
    R.drawable.orange2,
    R.drawable.pancake,
    R.drawable.pancakes,
    R.drawable.papaya,
    R.drawable.papaya2,
    R.drawable.peach,
    R.drawable.peach2,
    R.drawable.peanut,
    R.drawable.peanut_butter,
    R.drawable.pear_green,
    R.drawable.pear_green2,
    R.drawable.pear_yellow,
    R.drawable.peas,
    R.drawable.pecan,
    R.drawable.pepper_grinder,
    R.drawable.pepper_shaker,
    R.drawable.pickles,
    R.drawable.pie,
    R.drawable.pie_slice,
    R.drawable.pie1,
    R.drawable.pine_nuts,
    R.drawable.pineapple,
    R.drawable.pistachio,
    R.drawable.pitahaya,
    R.drawable.pitahaya2,
    R.drawable.pizza,
    R.drawable.pizza_round,
    R.drawable.plastic_bottle,
    R.drawable.plum,
    R.drawable.plum2,
    R.drawable.popcorn,
    R.drawable.popsicle,
    R.drawable.pork,
    R.drawable.portobello,
    R.drawable.potato,
    R.drawable.pretzel,
    R.drawable.pumpkin,
    R.drawable.pumpkin2,
    R.drawable.radish,
    R.drawable.raspberry,
    R.drawable.rice,
    R.drawable.rice_cracker,
    R.drawable.roasted_chicken,
    R.drawable.rock_candy,
    R.drawable.rocket_popsicle,
    R.drawable.romaine_lettuce,
    R.drawable.rye,
    R.drawable.salad,
    R.drawable.salmon_fillet,
    R.drawable.salmon_steak,
    R.drawable.salt_shaker,
    R.drawable.sandwich,
    R.drawable.sandwich2,
    R.drawable.sausage,
    R.drawable.shrimp,
    R.drawable.skewer,
    R.drawable.sliced_bread,
    R.drawable.soda_can,
    R.drawable.soft_cream_cone,
    R.drawable.soft_drink,
    R.drawable.soup,
    R.drawable.spaghetti,
    R.drawable.squash,
    R.drawable.squash2,
    R.drawable.steak,
    R.drawable.steak_raw,
    R.drawable.strawberry,
    R.drawable.sugar_cubes,
    R.drawable.sugarcane,
    R.drawable.sundae,
    R.drawable.sushi_maki,
    R.drawable.sushi_nigiri,
    R.drawable.sweet_potato,
    R.drawable.sweet_potato2,
    R.drawable.t_bone_steak,
    R.drawable.t_bone_steak_raw,
    R.drawable.tangerine,
    R.drawable.tea,
    R.drawable.tea_kettle,
    R.drawable.teabag,
    R.drawable.teapot,
    R.drawable.toast,
    R.drawable.toast_marmalade,
    R.drawable.tomato,
    R.drawable.tomato2,
    R.drawable.turnip,
    R.drawable.wafer,
    R.drawable.waffle,
    R.drawable.walnut,
    R.drawable.watermelon,
    R.drawable.watermelon1,
    R.drawable.watermelon2,
    R.drawable.wedding_cake,
    R.drawable.wheat,
    R.drawable.whisky_bottle,
    R.drawable.whisky_glass,
    R.drawable.whole_grain_bread,
    R.drawable.wine_bottle,
    R.drawable.wine_cup,
    R.drawable.wine_cup2
    )

var itemNames = arrayOf(
    "almond",
    "apple green",
    "apple red",
    "apple yellow",
    "apple 2",
    "artichoke",
    "asparagus",
    "avocado",
    "avocado 2",
    "bacon",
    "banana",
    "banana split",
    "barley",
    "beans",
    "beef",
    "beer",
    "beer bottle",
    "beetroot",
    "bell pepper",
    "bell pepper green",
    "bell pepper yellow",
    "bell pepper 1",
    "bell pepper 2",
    "birthday cake",
    "biscotti",
    "blackberry",
    "blueberry",
    "bowl chopsticks",
    "brazil nut",
    "bread",
    "bread slice",
    "broccoli",
    "brown bread",
    "bubblegum",
    "bubblegum machine",
    "bun",
    "butter",
    "cabbage",
    "cake",
    "cake slice",
    "cake slice2",
    "candy",
    "candy cane",
    "canned food",
    "cantaloupe",
    "cantaloupe 1",
    "cantaloupe 2",
    "caramel apple",
    "carrot",
    "cashew nut",
    "cassava",
    "cassava 2",
    "cauliflower",
    "celery",
    "champagne",
    "cheese round",
    "cheese slice",
    "cheese wedge",
    "cherry",
    "cherry tomatoes",
    "chestnut",
    "chicken",
    "chicken leg",
    "chickpeas",
    "chili pepper",
    "chocolate bar",
    "chocolate bonbon",
    "chocolate chip cookie",
    "cocktail",
    "cocoa",
    "coconut",
    "coconut 2",
    "coffee",
    "coffee bean",
    "coffee pot",
    "cognac",
    "cola drink",
    "cookie",
    "cookie2",
    "corn cob",
    "cotton candy",
    "crab",
    "cracker",
    "cranberry",
    "croissant",
    "cucumber",
    "cupcake",
    "cutlet",
    "double popsicle",
    "doughnut",
    "eclair",
    "egg",
    "eggplant",
    "eggplant 2",
    "fig",
    "fig 2",
    "fish",
    "fish fillet",
    "flour",
    "french fries",
    "fried chicken leg",
    "fried egg",
    "frozen",
    "fruit squash",
    "fruitcake",
    "garlic",
    "glass bottle",
    "glass of milk",
    "goldenberry",
    "grapefruit",
    "grapefruit 2",
    "grapes green",
    "grapes red",
    "green beans",
    "ham",
    "hamburger",
    "hard boiled egg",
    "hazelnut",
    "honey",
    "hot chocolate",
    "hotdog",
    "ice cream bar",
    "ice cream cone",
    "ice cream cup",
    "ice cream double cone",
    "ice cubes",
    "jam",
    "ketchup",
    "kiwi 2",
    "leek",
    "lemon",
    "lemon 2",
    "lentils",
    "lettuce",
    "lime",
    "lime 2",
    "lobster",
    "lollipop 1",
    "macadamia nut",
    "macaron",
    "maple syrup",
    "maple syrup 2",
    "marshmallow",
    "mayonnaise",
    "meatballs",
    "milk carton",
    "milk gallon",
    "milkshake",
    "muffin",
    "mushrooms",
    "mushrooms ",
    "mustard",
    "noodles",
    "nut cake",
    "oats",
    "olives",
    "olives black",
    "omelette",
    "onion",
    "onion red",
    "onion red 2",
    "orange",
    "orange juice",
    "orange 2",
    "pancake",
    "pancakes",
    "papaya",
    "papaya 2",
    "peach",
    "peach 2",
    "peanut",
    "peanut butter",
    "pear green",
    "pear green 2",
    "pear yellow",
    "peas",
    "pecan",
    "pepper grinder",
    "pepper shaker",
    "pickles",
    "pie",
    "pie slice",
    "pie 1",
    "pine nuts",
    "pineapple",
    "pistachio",
    "pitahaya",
    "pitahaya 2",
    "pizza",
    "pizza round",
    "plastic bottle",
    "plum",
    "plum 2",
    "popcorn",
    "popsicle",
    "pork",
    "portobello",
    "potato",
    "pretzel",
    "pumpkin",
    "pumpkin2",
    "radish",
    "raspberry",
    "rice",
    "rice cracker",
    "roasted chicken",
    "rock candy",
    "rocket popsicle",
    "romaine lettuce",
    "rye",
    "salad",
    "salmon fillet",
    "salmon steak",
    "salt shaker",
    "sandwich",
    "sandwich 2",
    "sausage",
    "shrimp",
    "skewer",
    "sliced bread",
    "soda can",
    "soft cream cone",
    "soft drink",
    "soup",
    "spaghetti",
    "squash",
    "squash 2",
    "steak",
    "steak raw",
    "strawberry",
    "sugar cubes",
    "sugarcane",
    "sundae",
    "sushi maki",
    "sushi nigiri",
    "sweet potato",
    "sweet potato 2",
    "t-bone steak",
    "t-bone steak raw",
    "tangerine",
    "tea",
    "tea kettle",
    "teabag",
    "teapot",
    "toast",
    "toast marmalade",
    "tomato",
    "tomato 2",
    "turnip",
    "wafer",
    "waffle",
    "walnut",
    "watermelon",
    "watermelon 1",
    "watermelon 2",
    "wedding cake",
    "wheat",
    "whisky bottle",
    "whisky glass",
    "whole grain bread",
    "wine bottle",
    "wine cup",
    "wine cup 2"
)

